### ISSUE TITLE
20231004 Feedback

### ISSUE THREAD

**Issue by MisooKim2** [haegun2/C202309#1]
에러 있음. 아래 파일/에러메세지/솔루션을 확인하세요
- ERROR in challenge/week5/functionMulti
    - Error: conflicting types for 'multiF' [line 12]
        - 이유: 함수 원형과 선언부에 자료형이 맞지 않습니다. 
        - 해결: 원형과 선언부에 반환데이터 혹은 매개변수의 자료형을 동일하게 맞춰주세요 (예: 매개변수 자료형 맞추기)

워닝 있음. 아래 파일/워닝메세지/솔루션을 확인하세요
- WARNING in challenge/week5/functionMulti
    - Warning: return type of 'main' is not 'int' [line 5]
         - 이유: main의 반환값은 int 여야 합니다
         - 해결: void main()을 int main()으로 변경하고 마지막에 return 0;을 추가하세요.
    - Warning: format specifies type 'int' but the argument has type 'long' [line 7]
    - Warning: format specifies type 'int' but the argument has type 'long' [line 8]
    - Warning: format specifies type 'int' but the argument has type 'long' [line 9]
        - 이유: 서식지정자 %d는 int 데이터를 위한 지정자입니다
        - 해결: %d를 %ld로 바꾸세요
- WARNING in practice/week5/functionHap
    - Warning: return type of 'main' is not 'int' [line 5]
         - 이유: main의 반환값은 int 여야 합니다
         - 해결: void main()을 int main()으로 변경하고 마지막에 return 0;을 추가하세요.

**Comment by MisooKim2** [comment]
제가 수업시간에 void main() 함수에 대해 알려드렸었는데,
최근 컴파일러들이 해당 코드를 지양하는 추세라고 합니다.
하여 워닝 메세지에 추가되었으니 수정부탁드립니다.
관련하여 수업시간에 추가 공지하도록 하겠습니다.

**Comment by haegun2** [comment]
두 항목 void -> int main  로 수정하였고, 서식지정자 역시 long 에 맞는 %ld 로 수정 완료하였습니다!
